In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
cc_apps = pd.read_csv("../Week11/Resources11/cc_approvals.data", header = None)
cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [44]:
print(cc_apps.describe())
print('\n')
print(cc_apps.info())
print('\n')
cc_apps.tail(17)

               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       690 non-null    object
 1   1       690 non-null    object
 2   2       690 non-null    float64
 3   3       690 non-null    object
 4   4       690 non-null    object
 5   5       690 non-null    object
 6   6       690 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    int64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      690 non-null    object
 14  14      690 non-null    int64
 15  15      690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB
None

    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [45]:
cc_apps = cc_apps.replace('?', np.nan)
cc_apps.tail(17)

      0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [46]:
cc_apps.loc[[2,7,10,14]] = cc_apps.loc[[2,7,10,14]].fillna(np.mean)
print(cc_apps.isna().sum())

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64

In [47]:
for col in list(cc_apps): 
    if cc_apps[col].dtypes == 'object':
        # Fill object columns with mode (most frequent value)
        cc_apps[col] = cc_apps[col].fillna(cc_apps[col].mode()[0])
    elif cc_apps[col].dtypes == 'int':
        # Fill int columns with mean
        cc_apps[col] = cc_apps[col].fillna(np.mean(cc_apps[col]))
print(cc_apps.isna().sum())

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in list(cc_apps):
    if cc_apps[col].dtypes == 'object':
        cc_apps[col] = le.fit_transform(cc_apps[col])
print(cc_apps.head())

   0    1      2   3   4   5   6     7   8   9   10  11  12  13   14  15
0   1  156  0.000   1   0  12   7  1.25   1   1   1   0   0  68    0   0
1   0  328  4.460   1   0  10   3  3.04   1   1   6   0   0  11  560   0
2   0   89  0.500   1   0  10   3  1.50   1   0   0   0   0  96  824   0
3   1  125  1.540   1   0  12   7  3.75   1   1   5   1   0  31    3   0
4   1   43  5.625   1   0  12   7  1.71   1   0   0   0   2  37    0   0

In [49]:
from sklearn.model_selection import train_test_split
cc_apps = cc_apps.drop([11,13], axis = 1)
cc_apps = cc_apps.values
 
x, y = cc_apps[:,0:12], cc_apps[:, 13]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state= 42)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(462, 12) (462,)
(228, 12) (228,)

In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
rescaledx_train = scaler.fit_transform(x_train)
rescaledx_test = scaler.fit_transform(x_test)

print(rescaledx_train.shape)
print(rescaledx_test.shape)

(462, 12)
(228, 12)

In [55]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression


logreg = LogisticRegression()
logreg.fit(rescaledx_train, y_train)

y_pred = logreg.predict(rescaledx_test)
print("Accuracy of logistics regression classifier: ", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy of logistics regression classifier:  0.8421052631578947
[[94  9]
 [27 98]]

In [64]:
cc_apps = pd.read_csv("../Week11/Resources11/cc_approvals.data")
cc_apps.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [65]:
print(cc_apps.describe())
print('\n')

print(cc_apps.info())
print('\n')

cc_apps.tail(17) # or cc_apps.sample()

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.3+ KB
None

     b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
672  ?  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673  a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674  a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675  a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676  b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677  a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678  a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679  b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680  b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681  b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682  b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683  b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684  b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [68]:
print(cc_apps.corr(numeric_only = True))
#Drop the features 11 and 13
cc_apps = cc_apps.drop(cc_apps.columns[[11, 13]], axis=1)

# Split into train and test sets
cc_apps_train, cc_apps_test = train_test_split(cc_apps, test_size=0.33, random_state=42)

             0      1.25        01       0.1
0     1.000000  0.298714  0.271003  0.122935
1.25  0.298714  1.000000  0.322247  0.051267
01    0.271003  0.322247  1.000000  0.063616
0.1   0.122935  0.051267  0.063616  1.000000

In [70]:
cc_apps_train = cc_apps_train.replace('?', np.nan)
cc_apps_test = cc_apps_test.replace('?', np.nan)
print(cc_apps_test)
print(cc_apps_train)

     b  30.83       0  u  g   w  v   1.25  t t.1  01   0.1
286  b  29.50   0.580  u  g   w  v  0.290  f   t   1  2803
655  b  25.67   3.250  u  g   c  h  2.290  f   t   1    21
257  a  20.75   9.540  u  g   i  v  0.040  f   f   0  1000
336  a  34.83   1.250  y  p   i  h  0.500  f   f   0     0
318  b  36.75   0.125  y  p   c  v  1.500  f   f   0   113
..  ..    ...     ... .. ..  .. ..    ... ..  ..  ..   ...
375  b  28.67  14.500  u  g   d  v  0.125  f   f   0   286
234  a  20.67   1.835  u  g   q  v  2.085  t   t   5  2503
643  b  36.17   0.420  y  p   w  v  0.290  f   f   0     2
271  b  18.08   6.750  y  p   m  v  0.040  f   f   0     0
311  a  16.33   0.210  u  g  aa  v  0.125  f   f   0     1

[228 rows x 12 columns]
       b  30.83       0  u  g   w   v    1.25  t t.1  01   0.1
382    a  56.83   4.250  y  p  ff  ff   5.000  f   f   0     4
137    a  18.83   9.500  u  g   w   v   1.625  t   t   6   600
346    b  26.75   4.500  y  p   c  bb   2.500  f   f   0  1210
326  NaN  40.83   3.500  u  g   i  bb   0.500  f   f   0     0
33     a  22.58  10.750  u  g   q   v   0.415  t   t   5   560
..   ...    ...     ... .. ..  ..  ..     ... ..  ..  ..   ...
71     a  38.58   5.000  u  g  cc   v  13.500  t   f   0     0
106    a  25.00  11.000  y  p  aa   v   4.500  t   f   0     0
270    b  32.33   2.500  u  g   c   v   1.250  f   f   0     0
435    b  19.58   0.585  u  g  ff  ff   0.000  f   t   3   769
102    b  25.00  12.000  u  g   k   v   2.250  t   t   2     5

[461 rows x 12 columns]

In [71]:
for col in cc_apps_train.columns: # Iterate over each column of cc_apps_train

    if cc_apps_train[col].dtypes == 'object': # Check if the column is of object type
        # Impute with the most frequent value
        # The value_counts() function returns a Series that contain counts of unique values. It returns an object that will be in 
        # descending order so that its first element will be the most frequently-occurred element.
        cc_apps_train = cc_apps_train.fillna(cc_apps_train[col].value_counts().index[0])
        cc_apps_test = cc_apps_test.fillna(cc_apps_train[col].value_counts().index[0])

# Count the number of NaNs in the dataset and print the counts to verify
print(cc_apps_train.isnull().sum()) 
print(cc_apps_test.isnull().sum())
# At this point, there is no missing values.

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
0.1      0
dtype: int64
b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
0.1      0
dtype: int64

In [73]:
print(cc_apps_train)
cc_apps_train = pd.get_dummies(cc_apps_train)
cc_apps_test = pd.get_dummies(cc_apps_test)
print(cc_apps_train)
cc_apps_test = cc_apps_test.reindex(columns = cc_apps_train.columns, fill_value=0)

          0    1.25  01   0.1    b_a    b_b  30.83_13.75  30.83_15.17  \
382   4.250   5.000   0     4   True  False        False        False
137   9.500   1.625   6   600   True  False        False        False
346   4.500   2.500   0  1210  False   True        False        False
326   3.500   0.500   0     0  False   True        False        False
33   10.750   0.415   5   560   True  False        False        False
..      ...     ...  ..   ...    ...    ...          ...          ...
71    5.000  13.500   0     0   True  False        False        False
106  11.000   4.500   0     0   True  False        False        False
270   2.500   1.250   0     0  False   True        False        False
435   0.585   0.000   3   769  False   True        False        False
102  12.000   2.250   2     5  False   True        False        False

     30.83_15.83  30.83_16.00  ...    v_h    v_j    v_n    v_o    v_v    v_z  \
382        False        False  ...  False  False  False  False  False  False
137        False        False  ...  False  False  False  False   True  False
346        False        False  ...  False  False  False  False  False  False
326        False        False  ...  False  False  False  False  False  False
33         False        False  ...  False  False  False  False   True  False
..           ...          ...  ...    ...    ...    ...    ...    ...    ...
71         False        False  ...  False  False  False  False   True  False
106        False        False  ...  False  False  False  False   True  False
270        False        False  ...  False  False  False  False   True  False
435        False        False  ...  False  False  False  False  False  False
102        False        False  ...  False  False  False  False   True  False

       t_f    t_t  t.1_f  t.1_t
382   True  False   True  False
137  False   True  False   True
346   True  False   True  False
326   True  False   True  False
33   False   True  False   True
..     ...    ...    ...    ...
71   False   True   True  False
106  False   True   True  False
270   True  False   True  False
435   True  False  False   True
102  False   True  False   True

[461 rows x 324 columns]
          0    1.25  01   0.1    b_a    b_b  30.83_13.75  30.83_15.17  \
382   4.250   5.000   0     4   True  False        False        False
137   9.500   1.625   6   600   True  False        False        False
346   4.500   2.500   0  1210  False   True        False        False
326   3.500   0.500   0     0  False   True        False        False
33   10.750   0.415   5   560   True  False        False        False
..      ...     ...  ..   ...    ...    ...          ...          ...
71    5.000  13.500   0     0   True  False        False        False
106  11.000   4.500   0     0   True  False        False        False
270   2.500   1.250   0     0  False   True        False        False
435   0.585   0.000   3   769  False   True        False        False
102  12.000   2.250   2     5  False   True        False        False

     30.83_15.83  30.83_16.00  ...    v_h    v_j    v_n    v_o    v_v    v_z  \
382        False        False  ...  False  False  False  False  False  False
137        False        False  ...  False  False  False  False   True  False
346        False        False  ...  False  False  False  False  False  False
326        False        False  ...  False  False  False  False  False  False
33         False        False  ...  False  False  False  False   True  False
..           ...          ...  ...    ...    ...    ...    ...    ...    ...
71         False        False  ...  False  False  False  False   True  False
106        False        False  ...  False  False  False  False   True  False
270        False        False  ...  False  False  False  False   True  False
435        False        False  ...  False  False  False  False  False  False
102        False        False  ...  False  False  False  False   True  False

       t_f    t_t  t.1_f  t.1_t
382   True  False   True  False
137  False   True  False   True
346   True  False   True  False
326   True  False   True  False
33   False   True  False   True
..     ...    ...    ...    ...
71   False   True   True  False
106  False   True   True  False
270   True  False   True  False
435   True  False  False   True
102  False   True  False   True

[461 rows x 324 columns]

In [74]:
x_train, y_train = cc_apps_train.iloc[:, :-1].values, cc_apps_train.iloc[:,[-1]].values
x_test, y_test = cc_apps_test.iloc[:, :-1].values, cc_apps_test.iloc[:,[-1]].values

scaler = MinMaxScaler(feature_range=(0,1))
rescaledx_train = scaler.fit_transform(x_train)
rescaledx_test  = scaler.fit_transform(x_test)

In [75]:
logreg = LogisticRegression()
logreg.fit(rescaledx_train, y_train)

y_pred = logreg.predict(rescaledx_test)
print("Accuarcy of logistics regression classifier: ", logreg.score(rescaledx_test, y_test))
confusion_matrix(y_test, y_pred)

Accuarcy of logistics regression classifier:  1.0

C:\Users\bell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[125,   0],
       [  0, 103]])

In [83]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

param_grid = {
    'n_neighbors': np.arange(1, 11),
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p': [1, 2]
}

# Define the KNN classifier
knn = KNeighborsClassifier()

# Define and fit the grid search
grid = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid.fit(rescaledx_train, y_train.ravel())

# Evaluate the best model on the test set
best_knn = grid.best_estimator_
y_pred_knn = best_knn.predict(rescaledx_test)
test_acc = accuracy_score(y_test.ravel(), y_pred_knn)

print("Best Hyperparameters:", grid.best_params_)
print("Best k value:", grid.best_params_['n_neighbors'])
print("Best CV Accuracy:", grid.best_score_)
print("Test Accuracy:", test_acc)
print("Confusion Matrix:\n", confusion_matrix(y_test.ravel(), y_pred_knn))
print("\nClassification Report:\n", classification_report(y_test.ravel(), y_pred_knn))

Best Hyperparameters: {'algorithm': 'auto', 'n_neighbors': np.int64(8), 'p': 1, 'weights': 'distance'}
Best k value: 8
Best CV Accuracy: 0.9218326320710613
Test Accuracy: 0.8947368421052632
Confusion Matrix:
 [[118   7]
 [ 17  86]]

Classification Report:
               precision    recall  f1-score   support

       False       0.87      0.94      0.91       125
        True       0.92      0.83      0.88       103

    accuracy                           0.89       228
   macro avg       0.90      0.89      0.89       228
weighted avg       0.90      0.89      0.89       228